
version: 2

jobs:
  nightly_build:
    docker:
      - image: rustlang/rust:nightly
    
    steps:
        - checkout
        - run:
            command: |
                rustup run nightly rustc --version
                rustup run nightly cargo --version
        - run:
            command: |
                rustup run nightly cargo build
        - run:
            command: |
                rustup run nightly cargo test

workflows:
  version: 2
  build:
    jobs: 
      - nightly_build


      
